---

php_debian_default_version: '7.0'

__php_version: '{{ php_debian_default_version }}'

php_web_server_daemon: apache2
php_fpm_bin: php-fpm{{ php_version }}
php_fpm_daemon: php{{ php_version }}-fpm

php_base_packages:
  - php{{ php_version }}
  - php{{ php_version }}-cli
  - php{{ php_version }}-common
  - php{{ php_version }}-fpm

php_conf_dir:
  - /etc/php/{{ php_version }}/apache2
  - /etc/php/{{ php_version }}/cli
  - /etc/php/{{ php_version }}/fpm

php_fpm_user: www-data
php_fpm_group: www-data

php_fpm_listen_owner: www-data
php_fpm_listen_group: www-data

php_fpm_pool_conf_path: /etc/php/{{ php_version }}/fpm/pool.d
