---

__php_version: 7.2

php_web_server_enabled: true
php_fpm_enabled: false

php_remi_repo_enabled: true   # Enable REMI repo on RHEL OS only
php_sury_repo_enabled: true   # Enable Sury repo on Debian OSs only

php_extra_packages: []

php_ini_disable_functions: []
php_ini_expose_php: 'Off'
php_ini_max_execution_time: '30'
php_ini_max_input_time: '60'
php_ini_max_input_vars: '2500'
php_ini_memory_limit: '128M'

php_ini_date_timezone: Asia/Jakarta

# PHP FPM configuration list
php_fpm_listen: '127.0.0.1:9000'
php_fpm_pm: dynamic                   # PHP FPM process manager (dynamic, static, ondemand)
php_fpm_pm_max_children: '50'         # The max number of child processes to be created
php_fpm_pm_start_servers: '5'
php_fpm_pm_min_spare_servers: '5'
php_fpm_pm_max_spare_servers: '20'
php_fpm_pm_max_requests: '4000'       # The number of requests each child process should execute before respawning
php_fpm_pm_process_idle_timeout: 10s  # The number of seconds after which an idle process will be killed

php_fpm_pool_template: php_fpm_pool.conf.j2

php_fpm_pools: []
# - name: www
#   filename: www.conf
#   listen: /var/run/php-fpm/php-fpm.sock
#   listen_allowed_clients: '127.0.0.1'
#   env_vars: |
#     env[HOSTNAME] = $HOSTNAME
#     env[PATH] = /usr/local/bin:/usr/bin:/bin
#     env[TMP] = /tmp
#     env[TMPDIR] = /tmp
#     env[TEMP] = /tmp
