---
dependencies: []

galaxy_info:
  role_name: php
  author: Agnesius Santo Naibaho
  description: Install PHP on Linux server
  company: "Cloudweeb"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.7
  platforms:
    - name: EL
      versions:
        - 7
    - name: Debian
      versions:
        - stretch
  galaxy_tags: []
