---
- name: Converge
  hosts: all

  vars:
    php_web_server_enabled: false
    php_fpm_enabled: true

    php_version: '7.2'

    php_fpm_pools:                # List of php-fpm pools that will be set
      - name: www
        filename: www.conf
        listen: 127.0.0.1:9101
        listen_allowed_clients: '127.0.0.1'
        env_vars: |
          env[HOSTNAME] = $HOSTNAME
          env[PATH] = /usr/local/bin:/usr/bin:/bin
          env[TMP] = /tmp
          env[TMPDIR] = /tmp
          env[TEMP] = /tmp
        extra_php_ini: |
          php_admin_value[error_log] = /var/log/php-fpm/www-error.log
          php_admin_flag[log_errors] = on
          php_admin_value[memory_limit] = 128M

  roles:
    - role: cloudweeb.php
