---

- name: Include OS-specific variables.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Define PHP version
  set_fact:
    php_version: "{{ __php_version }}"
  when: php_version is not defined

- name: Define PHP packages
  set_fact:
    php_packages: "{{ php_base_packages + php_extra_packages }}"

- name: Define PHP repository
  set_fact:
    php_repository: remi,remi-php{{ php_version | replace('.', '') }}
  when: php_version is defined and ansible_os_family == 'RedHat'

- import_tasks: repositories.yml

- import_tasks: install.yml

- import_tasks: configure.yml
