---

- name: MySQL secure install | Disallow root login remotely
  command: >
    mysql -NBe "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');"
  changed_when: false

- name: MySQL secure install | Set root password
  mysql_user:
    name: root
    password: "{{ mariadb_root_password }}"
    host_all: true
    state: present

- name: Set my.cnf file with root password credentials
  copy:
    content: |
      [client]
      user="root"
      password="{{ mariadb_root_password }}"
    dest: /root/.my.cnf
    mode: 0600
  no_log: true

- name: MySQL secure install | Remove anonymous users
  mysql_user:
    name: ''
    host_all: true
    state: absent

- name: MySQL secure install | Remove test database
  mysql_db:
    name: test
    state: absent
